### ISSUE TITLE
PHP Config tweak 'opcache.enable_file_override=1' breaks updater

### ISSUE THREAD

**Issue by kr31n3r** [shopware/docs#777]
`opcache.enable_file_override=1` is probably returning stale data and you will encounter errors like this while updating via admin-backend:

```
{"code":0,"message":"The file "vendor/react/promise/src/functions.php" was not supposed to exist.","file":"YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php","line":63,"trace":"#0 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Update/src/Steps/UnpackStep.php(111): GaufretteFilesystem->rename()n#1 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Update/src/Controller/BatchController.php(95): ShopwareRecoveryUpdateStepsUnpackStep->run()n#2 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Update/src/app.php(96): ShopwareRecoveryUpdateControllerBatchController->unpack()n#3 [internal function]: Closure->{closure}()n#4 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()n#5 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/Route.php(281): SlimHandlersStrategiesRequestResponse->__invoke()n#6 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): SlimRoute->__invoke()n#7 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/Route.php(268): SlimRoute->callMiddlewareStack()n#8 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(503): SlimRoute->run()n#9 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Update/src/app.php(71): SlimApp->__invoke()n#10 [internal function]: Closure->{closure}()n#11 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()n#12 [internal function]: SlimDeferredCallable->__invoke()n#13 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()n#14 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): SlimApp->Slim{closure}()n#15 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(392): SlimApp->callMiddlewareStack()n#16 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(297): SlimApp->process()n#17 YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Update/index.php(39): SlimApp->run()n#18 YOUR_SHOPWARE_ROOT/public/recovery/update/index.php(6): require_once('...')n#19 {main}"}
```

`YOUR_SHOPWARE_ROOT/vendor/shopware/recovery/Common/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php` at line `63` throws `UnexpectedFile($targetKey)`:

```
 55     public function rename($sourceKey, $targetKey)
 56     {
 57         self::assertValidKey($sourceKey);
 58         self::assertValidKey($targetKey);
 59
 60         $this->assertHasFile($sourceKey);
 61
 62         if ($this->has($targetKey)) {
 63             throw new Exception\UnexpectedFile($targetKey);
 64         }
 65
 66         if (!$this->adapter->rename($sourceKey, $targetKey)) {
 67             throw new \RuntimeException(sprintf('Could not rename the "%s" key to "%s".', $sourceKey, $targetKey));
 68         }
 69
 70         if ($this->isFileInRegister($sourceKey)) {
 71             $this->fileRegister[$targetKey] = $this->fileRegister[$sourceKey];
 72             unset($this->fileRegister[$sourceKey]);
 73         }
 74
 75         return true;
 76     }
```

Tested and reproducible with common PHP versions (`7.4`, `8.0`, `8.1`) while upgrading from shopware `6.4.17.0` to `6.4.17.2`... but other updates will probably fail as well.

see also: https://forum.shopware.com/search?q=%22was%20not%20supposed%20to%20exist%22

**Comment by sushmangupta** [comment]
Hey, 
Thanks for reaching out.
We will update the docs with the corresponding hint. :)

**Comment by shyim** [comment]
Just add a hint to the docs that this is not working with the web updater and maybe nobody should use that on a professional system
